<?php
$title = 'Edit ' . $entityName;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>



<?php
$form->setAttribute('action', $this->url($route, array_merge($controllerRoute, array('action' => 'edit', 'id' => ${$entityName}->getId()))));
$form->setAttribute('class', 'form-horizontal');

echo $this->ztbForm($form);
?>

<script type="text/javascript">
<?php foreach ($collections as $collection) : ?>
        $("#add<?= $collection ?>").click(function () {
            var template = $('form > fieldset > span').data('template');
            template = template.replace(/__index__/g, $("[id^='fieldset-<?= $collection ?>[']").length);
            $('form > fieldset').append(template);
            return false;
        });
        $("#remove<?= $collection ?>").click(function () {
            var currentCount = $("[id^='fieldset-<?= $collection ?>[']").length - 1;
            $('#fieldset-tags\\[' + currentCount + '\\]').remove();
            return false;
        });
<?php endforeach; ?>
</script>
