<?php
$title = 'Taggables';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('zfcrud/default', array('controller' => 'taggable', 'action' => 'add')); ?>">Add new taggable</a></p>
<table class="table table-bordered table-hover">
  <tr>
    <th>Taggable</th>
    <!--<th>&nbsp;</th>-->
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>
  <?php foreach ($taggables as $taggable) : ?>
      <tr>
        <td><?php echo $this->escapeHtml($taggable->getName()); ?></td>
        <!--<td>-->
            <!--<a href="<?php echo $this->url('zfcrud', array('action' => 'view', 'id' => $taggable->getId())); ?>">View</a>-->
        <!--</td>-->
        <td>
          <a href="<?php echo $this->url('zfcrud/default', array('controller' => 'taggable', 'action' => 'edit', 'id' => $taggable->getId())); ?>">Edit</a>
        </td>
        <td>
          <a href="<?php echo $this->url('zfcrud/default', array('controller' => 'taggable', 'action' => 'delete', 'id' => $taggable->getId())); ?>" onclick="return confirm('Are you sure?')">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>